site:
    siteURL: "https://stepanovplaton.ru/"
    title: "Степанов Платон"
    subtitle: ""
    lang: "ru"
    translate:
        enable: false
        service: "client.edge"
        showSelectTag: false
        autoDiscriminate: true
        ignoreClasses:
            - "ignore"
            - "banner-title"
            - "banner-subtitle"
        ignoreTags:
            - "script"
            - "style"
            - "code"
            - "pre"
    timeZone: 4
    font:
        "Example - ZenMaruGothic":
            src: "https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap"
            family: "Zen Maru Gothic"
    themeColor:
        hue: 90
        fixed: true
    defaultTheme: "dark"
    wallpaper:
        mode: "fullscreen"
        src:
            desktop:
                - "/assets/images/banner1.png"
            mobile:
                - "/assets/images/banner1.png"
        position: "center"
        carousel:
            enable: false
            interval: 12
            kenBurns: true
        banner:
            homeText:
                enable: true
                title: "Степанов Платон"
                subtitle:
                    - "Программный инженер, разработчик"
                typewriter:
                    enable: true
                    speed: 111
                    deleteSpeed: 51
                    pauseTime: 3000
            credit:
                enable: false
                text: "Describe"
                url: ""
            navbar:
                transparentMode: "semifull"
            waves:
                enable: true
                performanceMode: false
        fullscreen:
            zIndex: -1
            opacity: 0.7
            blur: 1
            navbar:
                transparentMode: "semi"
    loadingOverlay:
        enable: true
        title:
            enable: true
            content: "Загрузка..."
            interval: 1.5
        spinner:
            enable: true
            interval: 1.5
    favicon:
        -   src: "/favicon/favicon.ico"
            theme: "light"
            sizes: "96x96"
        -   src: "/favicon/favicon.ico"
            theme: "dark"
            sizes: "96x96"
    bangumi:
        userId: "your-bangumi-id"
    generateOgImages: false

umami:
    enabled: false
    baseUrl: "https://api.umami.is"
    apiKey: ""
    scripts: ""

navbar:
    links:
        -   "Projects"
        -   "Skills"
        -   "Timeline"
        # -   "Diary"
        -   "Albums"
        # -   "Friends"
        -   "WorthMentioning"
        -   "About"

sidebar:
    components:
        left:
            -   type: "profile"
                position: "top"
            #- 
            #    type: "announcement"
            #    position: "top"
            -   type: "categories"
                position: "sticky"
                responsive:
                    collapseThreshold: 5
            -   type: "tags"
                position: "sticky"
                responsive:
                    collapseThreshold: 20
        right:
            -   type: "toc"
                position: "sticky"
                customProps:
                    depth: 3
            #-   type: "statistics"
            #    position: "sticky"
profile:
    avatar: "/assets/images/avatar.jpg"
    name: "Степанов Платон"
    bio: "Приятно познакомиться!"
    links:
        -   name: "Git"
            icon: "fa6-brands:git-alt"
            url: "https://git.stepanovplaton.ru"
        -   name: "Telegram"
            icon: "fa6-brands:telegram"
            url: "https://t.me/StepanovPlaton"
        -   name: "HeadHunter"
            rawIcon: '<svg width="25" height="25" viewBox="0 0 400 400" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M400 200C400 310.457 310.457 400 200 400C89.5431 400 0 310.457 0 200C0 89.5431 89.5431 0 200 0C310.457 0 400 89.5431 400 200ZM160.34 161.226C146.98 161.226 136.74 166.526 130.84 176.486V127.126H99.8802V262.406H130.84V214.846C130.84 203.766 133.16 196.666 136.64 192.486C140.02 188.326 144.76 186.706 149.9 186.706C154.44 186.706 158.02 188.126 160.54 190.686C163.06 193.346 164.5 197.406 164.5 203.086V262.286H195.46V197.126C195.46 186.046 192.18 177.046 185.98 170.786C179.88 164.546 171.08 161.226 160.34 161.226ZM299.58 170.886C293.38 164.626 284.58 161.226 273.84 161.226C260.48 161.226 250.24 166.526 244.34 176.486V127.126H213.38V262.406H244.34V214.846C244.34 203.766 246.66 196.666 250.14 192.486C253.52 188.326 258.26 186.706 263.4 186.706C267.94 186.706 271.52 188.126 274.04 190.686C276.56 193.346 278 197.406 278 203.086V262.286H308.96V197.126C308.98 186.046 305.68 177.046 299.58 170.886Z" fill="currentColor"/></svg>'
            url: "/assets/Резюме_Степанов_Платон.pdf"
        -   name: "Email"
            icon: "material-symbols:mail-outline"
            copy: "mail2platon@yandex.ru" 

announcement:
    enable: false

post:
    showLastModified: true
    showCoverInContent: false
    expressiveCode:
        theme: "github-dark"
    license:
        enable: true
        name: "CC BY-NC-SA 4.0"
        url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    comment:
        enable: false
        twikoo:
            envId: "https://twikoo.vercel.app"
            lang: "en"

footer:
    enable: false
particle:
    enable: false

musicPlayer:
    enable: true
    mode: "local"
    local:
        playlist:
            -   id: 1
                title: "Children of the Omnissiah (Warhammer 40,000: Mechanicus OST)"
                artist: "Guillaume David"
                cover: "assets/images/war.jpg"
                url: "assets/music/war.mp3"
                duration: 106
            -   id: 2
                title: "Move (Rimworld P-Music)"
                artist: "Peppsen"
                cover: "assets/images/rimworld.jpg"
                url: "assets/music/rimworld.mp3"
                duration: 204
            -   id: 3
                title: "Reflecting"
                artist: "Michael Regner"
                cover: "assets/images/reflecting.jpg"
                url: "assets/music/reflecting.mp3"
                duration: 90
    autoplay: false

pio:
    enable: false