site:
    siteURL: "https://stepanovplaton.ru/"
    title: "Степанов Платон"
    subtitle: ""
    lang: "ru"
    translate:
        enable: false
        service: "client.edge"
        showSelectTag: false
        autoDiscriminate: true
        ignoreClasses:
            - "ignore"
            - "banner-title"
            - "banner-subtitle"
        ignoreTags:
            - "script"
            - "style"
            - "code"
            - "pre"
    timeZone: 4
    font:
        "Example - ZenMaruGothic":
            src: "https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap"
            family: "Zen Maru Gothic"
    themeColor:
        hue: 90
        fixed: true
    defaultTheme: "dark"
    wallpaper:
        mode: "fullscreen"
        src:
            desktop:
                - "/assets/images/banner1.png"
            mobile:
                - "/assets/images/banner1.png"
        position: "center"
        carousel:
            enable: true
            interval: 3.6
            kenBurns: true
        banner:
            homeText:
                enable: true
                title: "Степанов Платон"
                subtitle:
                    - "Программный инженер, разработчик"
                typewriter:
                    enable: true
                    speed: 111
                    deleteSpeed: 51
                    pauseTime: 3000
            credit:
                enable: false
                text: "Describe"
                url: ""
            navbar:
                transparentMode: "semifull"
            waves:
                enable: true
                performanceMode: false
        fullscreen:
            zIndex: -1
            opacity: 0.7
            blur: 1
            navbar:
                transparentMode: "semi"
    loadingOverlay:
        enable: true
        title:
            enable: true
            content: "Загрузка..."
            interval: 1.5
        spinner:
            enable: true
            interval: 1.5
    favicon:
        -   src: "/favicon/favicon.ico"
            theme: "light"
            sizes: "96x96"
        -   src: "/favicon/favicon.ico"
            theme: "dark"
            sizes: "96x96"
    bangumi:
        userId: "your-bangumi-id"
    generateOgImages: false

umami:
    enabled: false
    baseUrl: "https://api.umami.is"
    apiKey: ""
    scripts: ""

navbar:
    links:
        -   "Projects"
        -   "Skills"
        -   "Timeline"
        # -   "Diary"
        -   "Albums"
        # -   "Friends"
        -   "WorthMentioning"
        -   "About"

sidebar:
    components:
        left:
            -   type: "profile"
                position: "top"
            #- 
            #    type: "announcement"
            #    position: "top"
            -   type: "categories"
                position: "sticky"
                responsive:
                    collapseThreshold: 5
            -   type: "tags"
                position: "sticky"
                responsive:
                    collapseThreshold: 20
        right:
            -   type: "toc"
                position: "sticky"
                customProps:
                    depth: 3
            # -   type: "statistics"
            #     position: "sticky"
profile:
    avatar: "/assets/images/avatar.jpg"
    name: "Степанов Платон"
    bio: "Приятно познакомиться!"
    links:
        -   name: "Git"
            icon: "fa6-brands:git-alt"
            url: "https://git.stepanovplaton.ru"
        -   name: "Telegram"
            icon: "fa6-brands:telegram"
            url: "https://t.me/StepanovPlaton"
        -   name: "Email"
            icon: "material-symbols:mail-outline"
            url: "mailto:mail2platon@yandex.ru"

announcement:
    enable: false

post:
    showLastModified: true
    showCoverInContent: false
    expressiveCode:
        theme: "github-dark"
    license:
        enable: true
        name: "CC BY-NC-SA 4.0"
        url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    comment:
        enable: false
        twikoo:
            envId: "https://twikoo.vercel.app"
            lang: "en"

footer:
    enable: false
particle:
    enable: false

musicPlayer:
    enable: true
    mode: "local"
    local:
        playlist:
            -   id: 1
                title: "Children of the Omnissiah (Warhammer 40,000: Mechanicus OST)"
                artist: "Guillaume David"
                cover: "assets/images/war.jpg"
                url: "assets/music/war.mp3"
                duration: 106
            -   id: 2
                title: "Move (Rimworld P-Music)"
                artist: "Peppsen"
                cover: "assets/images/rimworld.jpg"
                url: "assets/music/rimworld.mp3"
                duration: 204
            -   id: 3
                title: "Reflecting"
                artist: "Michael Regner"
                cover: "assets/images/reflecting.jpg"
                url: "assets/music/reflecting.mp3"
                duration: 90
    autoplay: false

pio:
    enable: false